sudo: required
dist: trusty

language: cpp
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install -y cmake

install:
  - make -s V=1
  - make -s V=1 install

script:
  - make -s V=1 test
